package com.learn2crack.nfc.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.learn2crack.nfc.db.User;
import com.learn2crack.nfc.db.Scheduler;

import com.learn2crack.nfc.db.UserDao;
import com.learn2crack.nfc.db.SchedulerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig schedulerDaoConfig;

    private final UserDao userDao;
    private final SchedulerDao schedulerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        schedulerDaoConfig = daoConfigMap.get(SchedulerDao.class).clone();
        schedulerDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        schedulerDao = new SchedulerDao(schedulerDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Scheduler.class, schedulerDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        schedulerDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SchedulerDao getSchedulerDao() {
        return schedulerDao;
    }

}
