package com.learn2crack.nfc.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nfc_id = new Property(1, int.class, "nfc_id", false, "NFC_ID");
        public final static Property Phone_number = new Property(2, String.class, "phone_number", false, "PHONE_NUMBER");
        public final static Property Ride_left = new Property(3, Integer.class, "ride_left", false, "RIDE_LEFT");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NFC_ID\" INTEGER NOT NULL ," + // 1: nfc_id
                "\"PHONE_NUMBER\" TEXT," + // 2: phone_number
                "\"RIDE_LEFT\" INTEGER);"); // 3: ride_left
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNfc_id());
 
        String phone_number = entity.getPhone_number();
        if (phone_number != null) {
            stmt.bindString(3, phone_number);
        }
 
        Integer ride_left = entity.getRide_left();
        if (ride_left != null) {
            stmt.bindLong(4, ride_left);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNfc_id());
 
        String phone_number = entity.getPhone_number();
        if (phone_number != null) {
            stmt.bindString(3, phone_number);
        }
 
        Integer ride_left = entity.getRide_left();
        if (ride_left != null) {
            stmt.bindLong(4, ride_left);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // nfc_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // phone_number
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // ride_left
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNfc_id(cursor.getInt(offset + 1));
        entity.setPhone_number(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRide_left(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
